### ISSUE TITLE
bad news: different verifier with MSVC -flto

### ISSUE THREAD

**Issue by rurban** [c9fe/discohash#7]
Hi Cris,
I've added now LTO/IPO optimizations to smhasher, and MSVC creates now different code.
Looks like some typical msvc 32bit truncation going on.
I've got no testmachine, just appveyor.

https://github.com/rurban/smhasher/commit/10d0f41f4af7147c32d2141db011ff9ba8feffd5

**Comment by cris691** [comment]
Thanks @rurban I will take a look at this. Would it be too much trouble to explain a bit more what you mean by typical msvc 32 bit truncation?

**Comment by c9fe** [comment]
Yeah, I don't really care about this issue, @rurban
